### ISSUE TITLE
Condition assignment weights should allow decimals

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#23]
The UI allows you to input decimal weights (e.g. I have an experiment with 8 conditions, and I can set the weight to 12.5 for each), but the "assignments weights sum must be 100", so I assume the system considers decimals to be invalid.

I don't see any particular reason not to allow decimals.

I think there should be an "equal assignments" checkbox which just automatically updates the weights to add to 100 with equal values for all conditions. That's probably the most common case anyway.

**Comment by amurphy-cl** [comment]
Where are we on this one? Is this fixable by 2021/5/6?

**Comment by ppratikcr7** [comment]
Almost there, just need to figure out the backend table schema update. It should be fixed by 2021/5/6.

**Comment by ppratikcr7** [comment]
@amurphy-cl  I have created a [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/51) for it.

**Comment by amurphy-cl** [comment]
I'm trying to verify this but how do we want to manage e.g. three approximately-equally weighted conditions? If I set two to 33.3 and one to 33.4, I still get the "must sum to 100" error. Note that 66.6 and 33.4 doesn't work either. I suggest rounding the decimal places so we can enable these.

**Comment by amurphy-cl** [comment]
Thanks @ppratikcr7! My mistake, didn't notice it had yet to be merged :)

**Comment by amurphy-cl** [comment]
Waiting to see if this affects migration
